version: '3'

volumes:
    pgdata:
        driver: local

services:
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 8080
        ports:
          - "80:8080"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - backend
    backend:
        restart: always
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - ./Backend:/srv/www/Backend
        expose:
          - 8000
        ports:
            - 8000:8000

        command: "gunicorn -c gunicorn.py Backend.wsgi"
    postgres:
        image: postgres:9.3.22
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: postgresql_password
            POSTGRES_DB: database_name
            PGDATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data
